version: '3.8'

services:
  db:
    image: postgres:15
    container_name: LimbioKitchenPro-postgres
    environment:
      POSTGRES_USER: limbio
      POSTGRES_PASSWORD: amstel3229
      POSTGRES_DB: limbio_kitchen_pro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: limbio-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/limbio_kitchen_pro
      SPRING_DATASOURCE_USERNAME: limbio
      SPRING_DATASOURCE_PASSWORD: amstel3229
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
