version: "3.9"

services:
  backend:
    build: .
    container_name: limbio_kitchen_pro-backend
    environment:
      # Подключение к Neon
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-rapid-meadow-ah64j4q3-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_Oob21RXhWGeH
      # Настройки Spring Boot
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped
