version: '3.8'

services:
  app:
    image: backend-app
    container_name: limbio-backend
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/limbio_kitchen_pro
      SPRING_DATASOURCE_USERNAME: limbio
      SPRING_DATASOURCE_PASSWORD: amstel3229
    ports:
      - "8080:8080"

